---
sudo: required
language: python
services: docker

install:
  - pip install molecule[docker] --pre

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
