---

- name: Ensure CentOS Vault repositories list is up to date
  package:
    name: centos-release
    state: latest  # noqa 403
  retries: 10
  delay: 1
  when: ansible_distribution == 'CentOS'

- name: Get available kernel versions with YUM
  command: yum list --enablerepo=C7.* --showduplicates kernel
  changed_when: false
  args:
    warn: false
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"
  register: yum_kernel_list

- name: Set target YUM kernel version
  set_fact: _kernel="{{ yum_kernel_list |
                     rhel_kernel(kernel_version, ansible_kernel) }}"
  when: yum_kernel_list is not skipped

- name: Ensure kernel packages versions with YUM
  yum:
    name: "{{ item.name }}-{{ _kernel }}"
    enablerepo: "{{ yum_kernel_list |
                 rhel_repo(kernel_version, ansible_kernel) }}"
    allow_downgrade: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"
    - item.when
  with_items:
    - name: kernel
      when: true
    - name: kernel-devel
      when: install_kernel_headers | bool
    - name: kernel-headers
      when: install_kernel_headers | bool

- name: Get available kernel versions with DNF
  command: dnf list --enablerepo=* --showduplicates kernel
  changed_when: false
  args:
    warn: false
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version != "7"
  register: dnf_kernel_list

- name: Set target DNF kernel version
  set_fact: _kernel="{{ dnf_kernel_list |
                     rhel_kernel(kernel_version, ansible_kernel) }}"
  when: dnf_kernel_list is not skipped

- name: Ensure kernel packages versions with DNF
  dnf:
    name: "{{ item.name }}-{{ _kernel }}"
    enablerepo: "{{ dnf_kernel_list |
                 rhel_repo(kernel_version, ansible_kernel) }}"
    allow_downgrade: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version != "7"
    - item.when
  with_items:
    - name: kernel
      when: true
    - name: kernel-devel
      when: install_kernel_headers | bool
    - name: kernel-headers
      when: install_kernel_headers | bool

- name: Ensure APT cache is up to date
  apt:
    update_cache: true
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Get available kernel versions with APT
  command: apt-cache showpkg linux-headers-*
  changed_when: false
  when:
    - ansible_os_family == 'Debian'
  register: apt_kernel_list

- name: Get installed packages with APT
  command: dpkg -l
  changed_when: false
  when:
    - ansible_os_family == 'Debian'
  register: apt_packages_list

- name: Set target APT kernel version
  set_fact: _kernel="{{ apt_kernel_list |
                     deb_kernel(kernel_version, ansible_kernel) }}"
  when: apt_kernel_list is not skipped

- name: Ensure kernel packages versions with APT
  apt:
    name: "{{ apt_kernel_list | deb_kernel_pkg(
           kernel_version, ansible_kernel, ansible_distribution,
           ansible_architecture, item.name) }}"
  when:
    - ansible_os_family == 'Debian'
    - item.when
  with_items:
    - name: linux-image
      when: true
    - name: linux-headers
      when: install_kernel_headers | bool

- name: Ensure any other kernel packages are removed with APT
  apt:
    name: "{{ apt_packages_list | deb_installed_kernel(
           apt_kernel_list, kernel_version, ansible_kernel) }}"
    state: absent
    purge: true
  when: ansible_os_family == 'Debian'

- name: Get /var/run/reboot-required stat
  # Note: Should exist on Debian based OS if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_flag

- name: Notify about Kernel update and reboot requierement
  debug:
    msg: 'REBOOT REQUIRED, kernel version changed
          from {{ ansible_kernel }} to {{ _kernel }}.'
  when:
    - (not (ansible_kernel | kernel_match(_kernel)) or reboot_flag.stat.exists)

- name: Ensure the new kernel is enabled by rebooting
  reboot:
  when:
    - reboot_on_kernel_update | bool
    - (not (ansible_kernel | kernel_match(_kernel)) or reboot_flag.stat.exists)

- name: Update facts
  setup:
  when:
    - reboot_on_kernel_update | bool
    - (not (ansible_kernel | kernel_match(_kernel)) or reboot_flag.stat.exists)
