---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos_7
    image: centos:7
  - name: fedora_30
    image: fedora:30
  - name: debian_buster
    image: debian:buster
  - name: ubuntu_bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      centos_7:
        kernel_version: 3.10.0-693
      ubuntu_bionic:
        kernel_version: 4.15.0
verifier:
  name: testinfra
  lint:
    name: flake8
